version: '3'
services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html/
      - ./docker/nginx/sites/:/etc/nginx/conf.d/
      # - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - express
    networks:
      - app-network

  express:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express
    restart: unless-stopped
    working_dir: /var/www/html
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html
    command: npm run dev
    networks:
      - app-network
  mysql:
    image: "mysql:8.0"
    container_name: "mysql"
    restart: unless-stopped
    tty: true
    command: --sql_mode=''
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdatabase:/var/lib/mysql
    networks:
      - app-network
networks:
  app-network:
volumes:
  dbdatabase:
    driver: local
